RPGStatsEvents.heartTypes(event => {
  event.heartType('rpgstats:myofibra')
    .item('rpgstats:myofibra_heart')
    .asset('rpgstats:item/typed_hearts/myofibra')
    .displayName('Myofibra Heart')
    .catalyst('rpgstats:myofibra_catalyst')
    .consumeCatalyst(true)
    .channelTime(50)
    .priority(100)
    .requireRitualTierMin(1)
    .requireLevelMin(20)
    .requireStatMin('rpgstats:myofibra', 28)

  event.heartType('rpgstats:synapsis')
    .item('rpgstats:synapsis_heart')
    .asset('rpgstats:item/typed_hearts/synapsis')
    .displayName('Synapsis Heart')
    .catalyst('rpgstats:synapsis_catalyst')
    .consumeCatalyst(true)
    .channelTime(50)
    .priority(100)
    .requireRitualTierMin(2)
    .requireStatMin('rpgstats:synapsis', 30)
    .requireStatMin('rpgstats:carpus', 10)

  event.heartType('rpgstats:osteon')
    .item('rpgstats:osteon_heart')
    .asset('rpgstats:item/typed_hearts/osteon')
    .displayName('Osteon Heart')
    .catalyst('rpgstats:osteon_catalyst')
    .consumeCatalyst(true)
    .channelTime(60)
    .priority(110)
    .requireRitualTierMin(3)
    .requireStatMin('rpgstats:osteon', 36)
    .requireStatMin('rpgstats:hemostasis', 12)

  event.heartType('rpgstats:hemostasis')
    .item('rpgstats:hemostasis_heart')
    .asset('rpgstats:item/typed_hearts/hemostasis')
    .displayName('Hemostasis Heart')
    .catalyst('rpgstats:hemostasis_catalyst')
    .consumeCatalyst(true)
    .channelTime(60)
    .priority(110)
    .requireRitualTierMin(4)
    .requireLevelMin(30)
    .requireStatMin('rpgstats:hemostasis', 42)

  event.heartType('rpgstats:carpus')
    .item('rpgstats:carpus_heart')
    .asset('rpgstats:item/typed_hearts/carpus')
    .displayName('Carpus Heart')
    .catalyst('rpgstats:carpus_catalyst')
    .consumeCatalyst(true)
    .channelTime(70)
    .priority(120)
    .requireRitualTierMin(5)
    .requireDimension('minecraft:the_nether')
    .requireStatMin('rpgstats:carpus', 45)
    .requireStatMin('rpgstats:synapsis', 15)
})
